[Constants]
B0 = 14.1      # T
gamma = -4.316 # MHz/T
tp = 1       # s

# Longitudinal relaxation rate of abundant pool
[Variables.R1a] # Hz
vary = true
min = 0.1
max = 10
init = 5
#value = 1

# Transverse relaxation rate of abundant pool
[Variables.R2a] # Hz
vary = true
min = 1
max = 100
init = 50
#value = 10

# Larmor frequency of abundant pool relative to itself. Optimally zero.
[Variables.dwa] # ppm
vary = true
min = -1
max = 1
init = 0
#value = 0

# Longitudinal relaxation rate of dilute pool
[Variables.R1b] # Hz
vary = true
min = 0.1
max = 10
init = 5.05
# value =

# Transverse relaxation rate of dilute pool
[Variables.R2b] # Hz
vary = true
min = 1000
max = 100_000
init = 50500
# value =

# Forward exchange rate (dilute -> abundant pool)
[Variables.kb] # Hz
vary = true
min = 1
max = 100
init = 50.5
# value =

# Dilute pool equilibrium magnetization; fraction relative to abundant pool
[Variables.fb] # unitless, 0 to 1
vary = true
min = 1e-3
max = 0.1
init = 0.0505
# value =

# Larmor frequency of dilute pool relative to abundant pool
[Variables.dwb] # ppm
vary = true
 min = -1
 max = 1
 init = 0
#value = 0