[Constants]
B0 = 9.4      # T
gamma = 42.58 # MHz/T
tp = 10       # s

# Longitudinal relaxation rate of abundant pool
[Variables.R1a] # Hz
vary = false
# min =
# max =
# init =
value = 0.33

# Transverse relaxation rate of abundant pool
[Variables.R2a] # Hz
vary = false
# min =
# max =
# init =
value = 0.5

# Larmor frequency of abundant pool relative to itself. Optimally zero.
[Variables.dwa] # ppm
vary = false
# min =
# max =
# init =
value = 0

# Longitudinal relaxation rate of dilute pool
[Variables.R1b] # Hz
vary = true
min = 0.1
max = 10
init = 2
# value =

# Transverse relaxation rate of dilute pool
[Variables.R2b] # Hz
vary = true
min = 1
max = 100
init = 10
# value =

# Forward exchange rate (dilute -> abundant pool)
[Variables.kb] # Hz
vary = true
min = 50
max = 500
init = 100
# value =

# Dilute pool equilibrium magnetization; fraction relative to abundant pool
[Variables.fb] # unitless, 0 to 1
vary = true
min = 1e-5
max = 5e-3
init = 1e-3
# value =

# Larmor frequency of dilute pool relative to abundant pool
[Variables.dwb] # ppm
vary = false
# min = 0.01
# max = 1000
# init = 0.1
value = 3.5
