[Constants]
B0 = 9.4       # T
gamma = 16.546 # MHz/T
tp = 0.2       # s

# Longitudinal relaxation rate of abundant pool
[Variables.R1a] # Hz
vary = true
min = 1
max = 10
init = 5
#value = 8

# Transverse relaxation rate of abundant pool
[Variables.R2a] # Hz
vary = true
min = 100
max = 400
init = 250
# value = 380

# Larmor frequency of abundant pool relative to itself. Optimally zero.
[Variables.dwa] # ppm
vary = true
min = -10
max = 10
init = 0
#value = 0

# Longitudinal relaxation rate of dilute pool
[Variables.R1b] # Hz
vary = true
min = 0.1
max = 10
init = 5.05
#value = 1

# Transverse relaxation rate of dilute pool
[Variables.R2b] # Hz
vary = true
min = 10_000
max = 50_000
init = 30_000
# value =

# Forward exchange rate (dilute -> abundant pool)
[Variables.kb] # Hz
vary = true
min = 10
max = 1000
init = 550
# value =

# Dilute pool equilibrium magnetization; fraction relative to abundant pool
[Variables.fb] # unitless, 0 to 1
vary = true
min = 1e-3
max = 0.05
init = 0.0255
# value =

# Larmor frequency of dilute pool relative to abundant pool
[Variables.dwb] # ppm
vary = true
min = -300
max = -200
init = -250
# value = -260