[Constants]
B0 = 9.4       # T
gamma = 16.546 # MHz/T
tp = 0.2       # s

# Longitudinal relaxation rate of abundant pool
[Variables.R1a] # Hz
vary = false
# min =
# max =
# init =
value = 8

# Transverse relaxation rate of abundant pool
[Variables.R2a] # Hz
vary = true
min = 0.2
max = 4e4
init = 2
# value = 380

# Larmor frequency of abundant pool relative to itself. Optimally zero.
[Variables.dwa] # ppm
vary = true
min = -10
max = 10
init = 0
# value = 0

# Longitudinal relaxation rate of dilute pool
[Variables.R1b] # Hz
vary = false
# min = 0.01
# max = 1000
# init = 0.1
value = 1

# Transverse relaxation rate of dilute pool
[Variables.R2b] # Hz
vary = true
min = 0
max = 50_000
init = 50
# value =

# Forward exchange rate (dilute -> abundant pool)
[Variables.kb] # Hz
vary = true
min = 1
max = 1e6
init = 1000
# value =

# Dilute pool equilibrium magnetization; fraction relative to abundant pool
[Variables.fb] # unitless, 0 to 1
vary = true
min = 0
max = 9
init = 1e-4
# value =

# Larmor frequency of dilute pool relative to abundant pool
[Variables.dwb] # ppm
vary = true
min = -400
max = -200
init = -300
# value = -260
